Added init positional argument to create skeleton xedaproject.toml
XedaHQ/xeda pull request #8
Opened 2021-01-16 17:08 UTC by rishubn

Creates a `xedaproject.toml` template:

```
[project]
name = ""
description = ""

[[design]]
name = ""

[design.rtl]
sources = [ "src_rt/top.v",]
top = "Top"
clock = "clk"
[design.tb]
sources = [ "top_tb.vhd",]
top = "TopTB"

# Add another [[design]] below or add flow settings with [flows.<flow_name>].
# Example: [flows.vivado_sim].
# See xeda.readthedocs.io for the full list of flow settings
```

created with `xeda init` or `xeda init --xeda-project=path/to/xedaproject.toml`

2021-01-18 03:19 UTC, kammoh requested changes

2021-01-18 03:19 UTC, kammoh commented on xeda/xeda_app.py
> +                    "design":[{"name":"", "rtl":{"sources":["src_rt/top.v"], "top":"Top", "clock":"clk"}, "tb":{"sources":["top_tb.vhd"], "top":"TopTB"}}]}
Maybe just top.v or top.vhd?

2021-01-18 03:19 UTC, kammoh commented
This looks good, but probably needs rebase/restructure against the current master.

2021-01-19 12:34 UTC, rishubn commented on xeda/xeda_app.py
> +                    "design":[{"name":"", "rtl":{"sources":["src_rt/top.v"], "top":"Top", "clock":"clk"}, "tb":{"sources":["top_tb.vhd"], "top":"TopTB"}}]}
Changed to top.v

2021-01-20 15:36 UTC, kammoh commented
replaced by #10

2021-01-20 15:36 UTC, closed without merging